version: '3'

services:
  flask:
    image: flask-app
    networks:
      - search
    volumes:
      - ".:/usr/src"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9200:9200
    command: python app.py
  elastisearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    networks:
      - search
    environment:
      - discovery.type=single-node

networks:
  search:
    driver: bridge