version: '3'

services:
  microblog:
  # $ docker run --name microblog -d -p 8000:5000 --rm
  #   -e SECRET_KEY=my-secret-key \
  #   -e MAIL_SERVER=smtp.googlemail.com
  #   -e MAIL_PORT=587
  #   -e MAIL_USE_TLS=true
  #   -e MAIL_USERNAME=<your-gmail-username>
  #   -e MAIL_PASSWORD=<your-gmail-password>
  #   -e DATABASE_URL=mysql+pymysql://microblog:<database-password>@mysql/microblog
  #   --network microblog-network
  #   microblog:latest
    environment:
      - MAIL_SERVER=smtp.googlemail.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=true
      - DATABASE_URL=mysql+pymysql://microblog:$MYSQL_PASSWORD@mysql/microblog
    ports:
      - 8000:5000
    build: .
    volumes:
      - type: bind
        source: "."
        target: "/usr/src"
  elastisearch:
  # $ docker run --name elasticsearch -d --rm -p 9200:9200 \
  #   --memory="2GB" \
  #   -e discovery.type=single-node
  #   -e xpack.security.enabled=false \
  #   -t docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    expose:
      - "9200"
    mem_limit: 2g
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
  mysql:
  # $ docker run --name mysql -d
  #   -e MYSQL_RANDOM_ROOT_PASSWORD=yes
  #   -e MYSQL_DATABASE=microblog
  #   -e MYSQL_USER=microblog
  #   -e MYSQL_PASSWORD=<database-password>
  #   --network microblog-network
  #   mysql:latest
    image: mysql:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=microblog
    env_file: .env
    volumes:
      - type: bind
        source: "./data"
        target: "/var/lib/mysql"