"""new fields in the User model

Revision ID: 3115a27e34aa
Revises: f80747aacb7d
Create Date: 2024-02-18 01:05:02.694498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3115a27e34aa'
down_revision = 'f80747aacb7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
